PackageName: "JSOTemplate"
PackageOwner: "JuliaSmoothOptimizers"
PackageUUID: "adf32eb0-fe7e-47bb-93e4-fe96e72f6839"
_src_path: "https://github.com/JuliaSmoothOptimizers/JSOBestieTemplate.jl"
_commit: "v0.13.0"
AddBreakage: true
AddBenchmark: false
AddBenchmarkCI: true
