name: CompatHelper

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at 00:00 UTC
  workflow_dispatch:

jobs:
  compathelper:
    uses: JuliaSmoothOptimizers/.github/.github/workflows/CompatHelper.yml@move-scripts-to-github-JSO
