name: Invalidations

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  evaluate:
    uses: JuliaSmoothOptimizers/.github/.github/workflows/Invalidations.yml@move-scripts-to-github-JSO
    # later: @main after merge